import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../component/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Travel Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistMono.variable} ${geistSans.variable}`}>
      <body>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
